# Generated by Django 4.2.21 on 2025-06-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("desc", models.TextField(blank=True, max_length=256, null=True)),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField(null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
            options={
                "verbose_name_plural": "Products",
                "ordering": ["name"],
            },
        ),
    ]
